# Generated by Django 3.2.16 on 2023-02-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230221_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': ['id'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
